/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Sturij Brand Colors - Direct hex values
        'sage-green': {
          DEFAULT: '#4A5D4E',
          50: '#f6f7f6',
          100: '#e8eae9',
          200: '#d1d6d3',
          300: '#b0b8b4',
          400: '#8a9590',
          500: '#4A5D4E',
          600: '#3d4f42',
          700: '#334137',
          800: '#2b352f',
          900: '#252d27',
        },
        'warm-white': {
          DEFAULT: '#FAF8F3',
          50: '#FAF8F3',
          100: '#f5f3ee',
          200: '#ebe7dd',
          300: '#ddd7c7',
          400: '#ccc4b0',
          500: '#b8ad95',
          600: '#a39582',
          700: '#8a7b6b',
          800: '#72655a',
          900: '#5e544b',
        },
        'charcoal': {
          DEFAULT: '#2C2C2C',
          50: '#f6f6f6',
          100: '#e7e7e7',
          200: '#d1d1d1',
          300: '#b0b0b0',
          400: '#888888',
          500: '#6d6d6d',
          600: '#5d5d5d',
          700: '#4f4f4f',
          800: '#454545',
          900: '#2C2C2C',
        },
        'honey-gold': {
          DEFAULT: '#D4A574',
          50: '#fdf9f3',
          100: '#faf1e6',
          200: '#f4e0c7',
          300: '#ecc9a0',
          400: '#e2ad77',
          500: '#D4A574',
          600: '#c8874a',
          700: '#a8703e',
          800: '#895c36',
          900: '#704d30',
        },
        'soft-blue-grey': {
          DEFAULT: '#8B9CAD',
          50: '#f8f9fa',
          100: '#f1f3f5',
          200: '#e1e6ea',
          300: '#cbd4db',
          400: '#b0bcc7',
          500: '#8B9CAD',
          600: '#7a8a9a',
          700: '#6b7a88',
          800: '#5a6670',
          900: '#4c555c',
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: `calc(var(--radius) - 4px)`,
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}